[package]
name = "relay-tang-client"
version = "0.1.0"
edition = "2018"
# TODO: more info

[workspace]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }

headers-relay               = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-substrate-client      = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-utils                 = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }

# Supported Chains

tang-node-runtime = { path = "../../bin/tang/runtime" }

# Substrate Dependencies

frame-support = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
frame-system = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-core = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-keyring = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
