[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Tang node client for sub-sub bridge"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "relay-tang-client"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.2.3"

[dependencies]
codec                       = { package = "parity-scale-codec", version = "1.3.4" }
headers-relay               = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-substrate-client      = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-utils                 = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
# Supported Chains
darwinia-ethereum-relay     = {path = "../../frame/bridge/ethereum/relay"}
tang-node-primitives        = { path = "../../bin/tang/primitives" }
tang-node-runtime           = { path = "../../bin/tang/runtime" }
# Substrate Dependencies
frame-support               = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
frame-system                = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
pallet-transaction-payment  = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-core                     = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-keyring                  = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime                  = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
