[package]
name = "relay-song-client"
version = "0.1.0"
edition = "2018"
# TODO: more info

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4" }

headers-relay               = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-substrate-client      = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-utils                 = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }

# Bridge dependencies

song-node-runtime    = { path = "../../bin/song/runtime" }
song-node-primitives = { path = "../../bin/song/primitives" }
darwinia-ethereum-relay = {path = "../../frame/bridge/ethereum/relay"}


# Substrate Dependencies

frame-system = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
frame-support = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-core = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-keyring = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
