[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Minimal array/bytes operation for runtime"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "relay-song-client"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.2.3"

[dependencies]
codec                       = { package = "parity-scale-codec", version = "1.3.4" }
headers-relay               = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-substrate-client      = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-utils                 = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
# Bridge dependencies
darwinia-ethereum-relay     = { path = "../../frame/bridge/ethereum/relay"}
song-node-primitives        = { path = "../../bin/song/primitives" }
song-node-runtime           = { path = "../../bin/song/runtime" }
# Substrate Dependencies
frame-system                = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
frame-support               = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
pallet-transaction-payment  = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-core                     = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-keyring                  = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime                  = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
