[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "MODEXP precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-evm-precompile-modexp"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.0.0"


[dependencies]
# crates
dp-evm = { default-features = false, path = "../../../../../primitives/evm" }
evm    = { default-features = false, version = "0.23.0", features = ["with-codec"] }
num    = { default-features = false, version = "0.3", features = ["alloc"] }
# substrate
sp-core = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.2.1-darwinia" }
sp-io   = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.2.1-darwinia" }

[dev-dependencies]
hex = "0.4.0"

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"dp-evm/std",
	"evm/std",
	"num/std",
]

substrate-std = [
	"sp-core/std",
	"sp-io/std",
]
