[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia Relay Primitives"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-relay-primitives"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.4.0"

[dependencies]
# crates
codec = { package = "parity-scale-codec", version = "2.1.1", default-features = false }
hashbrown   = { version = "0.9.1" }
ethereum-primitives                = { default-features = false, path = "../ethereum-primitives" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
	"darwinia-std",
]

crates-std    = ["codec/std"]
substrate-std = [
	"frame-support/std",
	"sp-runtime/std",
	"sp-std/std",
]
darwinia-std = [
	"ethereum-primitives/std",
]

