[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Dynamic fee handling for EVM."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "dvm-dynamic-fee"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.3.0"


[dependencies]
codec               = { default-features = false, version = "1.3.6", package = "parity-scale-codec" }
serde               = { default-features = false, version = "1.0.123", optional = true, features = ["derive"] }

frame-support       = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
frame-system        = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-core             = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-inherents        = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime          = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-std              = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-std/std",
] 