[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "DRML node runtime primitives"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "song-node-primitives"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.0.1"

[dependencies]
# substrate primitives
sp-core    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-std    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-api    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }

bp-runtime          = { default-features = false, git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
bp-message-lane 	= { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear", default-features = false }

[features]
default = ["std"]

std = ["substrate-primitives-std"]

substrate-primitives-std = [
	"sp-core/std",
	"sp-runtime/std",
	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",
	"bp-runtime/std",
	"bp-message-lane/std",
]
