[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Minimal array/bytes operation for runtime"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "substrate-relay"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.2.3"

[dependencies]
async-std = "1.8.0"
async-trait = "0.1.42"
codec = { package = "parity-scale-codec", version = "1.3.4" }
futures = "0.3.8"
hex = "0.4"
log = "0.4.11"
num-traits = "0.2"
paste = "1.0"
structopt = "0.3"
# Bridge dependencies
bp-message-lane             = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
bp-runtime                  = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
headers-relay               = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
messages-relay              = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
pallet-bridge-call-dispatch = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
pallet-substrate-bridge     = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-song-client           = { path = "../song-client" }
relay-substrate-client      = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
relay-tang-client           = { path = "../tang-client" }
relay-utils                 = { git = "https://github.com/AsceticBear/parity-bridges-common.git", branch = "bear" }
song-node-runtime           = { path = "../../bin/song/runtime" }
song-node-primitives        = { path = "../../bin/song/primitives" }
tang-node-runtime           = { path = "../../bin/tang/runtime" }
tang-node-primitives        = { path = "../../bin/tang/primitives" }
# Substrate Dependencies
frame-support           = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-core                 = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-finality-grandpa     = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-runtime              = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
sp-trie                 = { git = "https://github.com/darwinia-network/substrate.git", branch = "common-library" }
