[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "DISPATCH precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-evm-precompile-dispatch"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.0.0"


[dependencies]
# crates
codec                   = { package = "parity-scale-codec", version = "1.3.7", default-features = false }
darwinia-evm            = { default-features = false, path = "../../../../evm" }
dp-evm = { default-features = false, path = "../../../../../primitives/evm" }
evm                     = { version = "0.23.0", features = ["with-codec"], default-features = false }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.2.1-darwinia" }
sp-core       = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.2.1-darwinia" }
sp-io         = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.2.1-darwinia" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"codec/std",
	"darwinia-evm/std",
	"dp-evm/std",
	"evm/std",
]

substrate-std = [
	"frame-support/std",
	"sp-core/std",
	"sp-io/std",
]
