[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to s2s chain"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-s2s-chain"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.4.0"

[dependencies]
# crates
codec          = { package = "parity-scale-codec", version = "2.1.1", default-features = false, features = ["derive"] }
# darwinia
darwinia-asset-primitives          = { default-features = false, path = "../../../../primitives/asset" }
darwinia-relay-primitives          = { default-features = false, path = "../../../../primitives/relay" }
ethereum-primitives                = { default-features = false, path = "../../../../primitives/ethereum-primitives" }
# substrate
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "s2s" }

[features]
default = ["std"]

std = [
	"darwinia-std",
	"substrate-std",
]

darwinia-std = [
	"darwinia-asset-primitives/std",
	"ethereum-primitives/std",
]

substrate-std = [
	"sp-std/std",
]
