[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "FRAME pallet to s2s backing"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-s2s-backing"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "2.4.0"

[dependencies]
# crates
codec          = { package = "parity-scale-codec", version = "2.1.1", default-features = false, features = ["derive"] }
ethereum-types = { default-features = false, version = "0.11.0" }
log            = { version = "0.4.14" }
serde          = { version = "1.0.126", optional = true }
serde_json     = { version = "1.0.64", optional = true }
array-bytes = { version = "1.3.3" }
# darwinia
darwinia-asset-primitives          = { default-features = false, path = "../../../../primitives/asset" }
darwinia-primitives-contract = { default-features = false, path = "../../../../primitives/contract" }
darwinia-relay-primitives          = { default-features = false, path = "../../../../primitives/relay" }
darwinia-support                   = { default-features = false, path = "../../../support" }
ethereum-primitives                = { default-features = false, path = "../../../../primitives/ethereum-primitives" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.1" }
frame-system  = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.1" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.1" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.11.1" }

[features]
default = ["std"]

std = [
	"substrate-std",
	"crates-std",
	"darwinia-std",
]

crates-std = [
	"codec/std",
	"ethereum-types/std",
	"serde",
	"serde_json",
]

darwinia-std = [
	"darwinia-asset-primitives/std",
	"darwinia-primitives-contract/std",
	"ethereum-primitives/std",
	"darwinia-relay-primitives/std",
	"darwinia-support/std",
]

substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std",
]
