name: CI
on:
  push:
    branches:
      - pangolin
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-09-20
          override: true
          target: wasm32-unknown-unknown

      # - name: Overall test
      #   run: cargo test
      
  dvm-rpc-test:
    name: Run dvm rpc Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-09-20
          override: true
          target: wasm32-unknown-unknown

      - name: Build and Run node
        run: | 
            cargo build --release
            ./target/release/drml --dev --tmp &
            ps -aux|grep drml
            sleep 100
            ps -aux|grep drml

      - name: Set up node env 
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Run dvm tests
        run: cd frame/dvm/script_tests/ && npm install && npm test

  clean:
    needs: dvm-rpc-test
    name: Stop Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  pkill -f drml 