[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Primitives for Darwinia EVM"
edition     = "2018"
homepage    = "https://substrate.dev"
license     = "Apache-2.0"
name        = "darwinia-evm-primitives"
readme      = "README.md"
repository  = "https://github.com/darwinia-network/darwinia-common/"
version     = "1.2.2"

[dependencies]
# crates
codec      = { package = "parity-scale-codec", version = "1.3.4", default-features = false }
evm        = { version = "0.18", default-features = false, features = ["with-codec"] }
serde      = { version = "1.0.101", optional = true, features = ["derive"] }
# substrate
sp-core   = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git", branch = "frontier", default-features = false }
sp-std    = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git", branch = "frontier", default-features = false }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"codec/std",
	"evm/std",
	"evm/with-serde",
	"serde",
]

substrate-std = [
	"sp-core/std",
	"sp-std/std",
]
